### ISSUE TITLE
Failed to activate the linter-handlebars package

### ISSUE THREAD

**Issue by davelovemartin** [josa42/atom-linter-handlebars#8]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [linter-handlebars](https://github.com/josa42/atom-linter-handlebars) package, v2.3.1
### Stack Trace

Failed to activate the linter-handlebars package

```
At packageName is required

Error: packageName is required
    at Object.install (/Users/justanotherdavemartin/.atom/packages/linter-handlebars/node_modules/atom-package-deps/lib/main.js:19:27)
    at Object.activate (/Users/justanotherdavemartin/.atom/packages/linter-handlebars/lib/init.js:9:17)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -1:06.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/justanotherdavemartin/Projects/",
    "disabledPackages": [
      "emmet"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-handlebars, v1.3.0
atom-jshint, v2.0.0
file-icons, v1.6.14
file-types, v0.5.1
language-spacebars, v0.2.2
linter, v1.11.3
linter-handlebars, v2.3.1
meteor-api, v2.20.0

# Dev
No dev packages
```

**Comment by josa42** [comment]
That's weird. I cannot reproduce this.

Can you give me more details?
1. Did this happen right after you updated linter-handlebars? Do you remember what the previous version was?
2. Did restart/reload atom solve the problem?
3. Did you try, uninstalling and reinstalling linter-handlebars?

**Comment by davelovemartin** [comment]
Restart/reload seemed to resolve.
